### ISSUE TITLE
Express ContainerRegistry, ContainerTag, and PullPolicy on the operator's CR

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/web-ui-operator#36]
/kind enhancement

Expose ContainerRegistry, ContainerTag, and PullPolicy on the operator's CR.

HCO's [configuration proposal](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/22)

**Comment by mareklibra** [comment]
PullPolicy: https://github.com/kubevirt/web-ui-operator/pull/38

**Comment by rthallisey** [comment]
in the first release, we're going to have minimal config.  The config options I posted here aren't needed.
