### ISSUE TITLE
Does this WebUI works only with Open Shift ? 

### ISSUE THREAD

**Issue by sacashgit** [kubevirt/web-ui-operator#94]
We have deployed Kubevirt (following the kubevirt.io docs) on open source kubernetes and were trying to see if we could get the WebUI on top it. The instructions listed here are all for Open Shift. Does the Web UI for Kubevirt works on open source kubernetes and where should we look for instructions?

**Comment by mareklibra** [comment]
It was tested on OpenShift (or OKD). As web-ui's key features are recently based on templates, additional changes to support upstream Kubernetes would need to be implemented (templates are add-on of OKD).

However please note, the kubevirt/web-ui (and related) functionality has been merged to https://github.com/openshift/console recently, making the web-ui-* projects deprecated.

Have you considered using the upstream OKD (formerly OpenShift, https://github.com/openshift)? Simply said, it contains Kubernetes and moves it towards PaaS (from IaaS) by adding features. In other words, what is supported in OKD, is still supported in OKD but adding more.

**Comment by Nurlan199206** [comment]
me too trying run it on kubernetes..

**Comment by jelkosz** [comment]
@Nurlan199206 this blog might help you a bit: https://kubevirt.io/2019/KubeVirt_UI_options.html 

Long story short, it kinda works on pure k8s but the VM wizard does not open. @glekner is now playing around with it to make it work.
